from datetime import datetime
from random import Random
from threading import Lock, Thread
from time import sleep

from sqlalchemy import func, select

from app.core.time_utils import utc_now
from app.db.session import SessionLocal
from app.models.runtime import JobRun, JobRunStage, RunFailureDetail

_ACTIVE_RUNS: set[str] = set()
_ACTIVE_RUNS_LOCK = Lock()

_STAGE_BASE_DURATION_MS = {
    "pre_filter": 420,
    "relevance_analysis": 980,
    "label_classify": 1320,
    "sentiment_analysis": 760,
}

_FAILURE_CATEGORIES = ["system_error", "model_error", "business_error", "transient_error"]
_FAILURE_ERROR_TYPES = ["timeout", "schema_mismatch", "label_empty", "parse_failed", "voc_irrelevant"]


def _safe_now() -> datetime:
    return utc_now()


def is_pipeline_run_active(run_id: str) -> bool:
    with _ACTIVE_RUNS_LOCK:
        return run_id in _ACTIVE_RUNS


def _mark_active(run_id: str) -> bool:
    with _ACTIVE_RUNS_LOCK:
        if run_id in _ACTIVE_RUNS:
            return False
        _ACTIVE_RUNS.add(run_id)
        return True


def _mark_done(run_id: str) -> None:
    with _ACTIVE_RUNS_LOCK:
        _ACTIVE_RUNS.discard(run_id)


def _build_failure_item(rng: Random, run_id: str, index: int, stage_name: str) -> RunFailureDetail:
    category = _FAILURE_CATEGORIES[rng.randrange(len(_FAILURE_CATEGORIES))]
    error_type = _FAILURE_ERROR_TYPES[rng.randrange(len(_FAILURE_ERROR_TYPES))]
    record_id = f"{run_id}-FAIL-{index + 1:03d}"
    return RunFailureDetail(
        run_id=run_id,
        record_id=record_id,
        category=category,
        node=stage_name,
        error_type=error_type,
        detail=f"Synthetic failure generated by staged pipeline service ({error_type})",
        input_payload={"record_id": record_id, "stage": stage_name},
        output_payload={"error_type": error_type, "category": category},
    )


def _execute_pipeline(run_id: str) -> None:
    rng = Random(run_id)

    try:
        with SessionLocal() as db:
            run = db.scalar(select(JobRun).where(JobRun.run_id == run_id))
            if run is None:
                return
            stages = db.scalars(select(JobRunStage).where(JobRunStage.run_id == run_id).order_by(JobRunStage.id)).all()
            if not stages:
                run.status = "failed"
                run.ended_at = _safe_now()
                db.commit()
                return

            if run.started_at is None:
                run.started_at = _safe_now()
            run.status = "running"
            if run.total_input <= 0:
                run.total_input = rng.randint(180, 620)
            db.commit()

            for stage in stages:
                stage.status = "running"
                stage.duration_ms = 0
                db.commit()

                sleep(0.45)
                duration = _STAGE_BASE_DURATION_MS.get(stage.stage_name, 700) + rng.randint(80, 420)
                stage.duration_ms = duration
                stage.status = "success"
                db.commit()

            failure_ratio = rng.uniform(0.0, 0.08)
            failed_count = int(run.total_input * failure_ratio)
            if failed_count <= 0 and rng.random() < 0.25:
                failed_count = 1
            failed_count = min(failed_count, max(1, run.total_input // 2))

            run.failed_count = failed_count
            run.success_count = max(0, run.total_input - failed_count)
            run.status = "partial_success" if failed_count > 0 else "success"
            run.ended_at = _safe_now()

            if failed_count > 0:
                existing_count = int(
                    db.scalar(select(func.count()).select_from(RunFailureDetail).where(RunFailureDetail.run_id == run_id))
                    or 0
                )
                if existing_count == 0:
                    failure_rows = min(8, failed_count)
                    for index in range(failure_rows):
                        stage_name = stages[(index + 1) % len(stages)].stage_name
                        db.add(_build_failure_item(rng=rng, run_id=run_id, index=index, stage_name=stage_name))

            db.commit()
    except Exception:
        with SessionLocal() as db:
            run = db.scalar(select(JobRun).where(JobRun.run_id == run_id))
            if run is not None:
                run.status = "failed"
                run.ended_at = _safe_now()
                db.commit()
    finally:
        _mark_done(run_id)


def run_pipeline_mock(run_id: str) -> dict:
    # Keep the original function name for API compatibility, but execute a staged run in background.
    if not _mark_active(run_id):
        return {"run_id": run_id, "status": "running", "mode": "staged"}

    worker = Thread(target=_execute_pipeline, args=(run_id,), daemon=True)
    worker.start()
    return {"run_id": run_id, "status": "running", "mode": "staged"}
